### PR TITLE
Add name to create source body model

### PR DESCRIPTION
**Pull request by ns-axu**
Adds the `name` attribute to the `CreateSourceBody` model so that the name can be explicitly set on source creation.

@jdrake fyi

### CODE REVIEW

**Review by CelestineKao — APPROVED** [review]

**Comment by jdrake** [comment]
Why is the CircleCI file changing?

**Comment by ns-axu** [comment]
i changed it because it was running the pre-commit test and failing on formatting/docstring issues on the autogenerated code

**Comment by jdrake** [comment]
Could you update the pre commit config instead? Nothing is sacrosanct in there so feel free to tweak or omit things as necessary. Not running the PR test at all is kind of a bludgeon.

**Comment by ns-axu** [comment]
Gotcha, i'll update. sorry about that

**Pull request merged**
